// db/mock/store.go

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/nibir1/go-fiber-postgres-REST-boilerplate/db/sqlc (interfaces: Store)

// Package mockdb is a generated GoMock package.
package mockdb

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	db "github.com/nibir1/go-fiber-postgres-REST-boilerplate/db/sqlc"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// CreateCourse mocks base method.
func (m *MockStore) CreateCourse(arg0 context.Context, arg1 db.CreateCourseParams) (db.Course, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCourse", arg0, arg1)
	ret0, _ := ret[0].(db.Course)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCourse indicates an expected call of CreateCourse.
func (mr *MockStoreMockRecorder) CreateCourse(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCourse", reflect.TypeOf((*MockStore)(nil).CreateCourse), arg0, arg1)
}

// CreateRecommendation mocks base method.
func (m *MockStore) CreateRecommendation(arg0 context.Context, arg1 db.CreateRecommendationParams) (db.Recommendation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRecommendation", arg0, arg1)
	ret0, _ := ret[0].(db.Recommendation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRecommendation indicates an expected call of CreateRecommendation.
func (mr *MockStoreMockRecorder) CreateRecommendation(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRecommendation", reflect.TypeOf((*MockStore)(nil).CreateRecommendation), arg0, arg1)
}

// CreateScholarship mocks base method.
func (m *MockStore) CreateScholarship(arg0 context.Context, arg1 db.CreateScholarshipParams) (db.Scholarship, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateScholarship", arg0, arg1)
	ret0, _ := ret[0].(db.Scholarship)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateScholarship indicates an expected call of CreateScholarship.
func (mr *MockStoreMockRecorder) CreateScholarship(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateScholarship", reflect.TypeOf((*MockStore)(nil).CreateScholarship), arg0, arg1)
}

// CreateSummary mocks base method.
func (m *MockStore) CreateSummary(arg0 context.Context, arg1 db.CreateSummaryParams) (db.Summary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSummary", arg0, arg1)
	ret0, _ := ret[0].(db.Summary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSummary indicates an expected call of CreateSummary.
func (mr *MockStoreMockRecorder) CreateSummary(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSummary", reflect.TypeOf((*MockStore)(nil).CreateSummary), arg0, arg1)
}

// CreateTranscript mocks base method.
func (m *MockStore) CreateTranscript(arg0 context.Context, arg1 db.CreateTranscriptParams) (db.Transcript, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTranscript", arg0, arg1)
	ret0, _ := ret[0].(db.Transcript)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTranscript indicates an expected call of CreateTranscript.
func (mr *MockStoreMockRecorder) CreateTranscript(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTranscript", reflect.TypeOf((*MockStore)(nil).CreateTranscript), arg0, arg1)
}

// CreateUser mocks base method.
func (m *MockStore) CreateUser(arg0 context.Context, arg1 db.CreateUserParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", arg0, arg1)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockStoreMockRecorder) CreateUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockStore)(nil).CreateUser), arg0, arg1)
}

// DeleteScholarship mocks base method.
func (m *MockStore) DeleteScholarship(arg0 context.Context, arg1 db.DeleteScholarshipParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteScholarship", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteScholarship indicates an expected call of DeleteScholarship.
func (mr *MockStoreMockRecorder) DeleteScholarship(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteScholarship", reflect.TypeOf((*MockStore)(nil).DeleteScholarship), arg0, arg1)
}

// DeleteSummary mocks base method.
func (m *MockStore) DeleteSummary(arg0 context.Context, arg1 db.DeleteSummaryParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSummary", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSummary indicates an expected call of DeleteSummary.
func (mr *MockStoreMockRecorder) DeleteSummary(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSummary", reflect.TypeOf((*MockStore)(nil).DeleteSummary), arg0, arg1)
}

// GetRecommendation mocks base method.
func (m *MockStore) GetRecommendation(arg0 context.Context, arg1 int64) (db.Recommendation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecommendation", arg0, arg1)
	ret0, _ := ret[0].(db.Recommendation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecommendation indicates an expected call of GetRecommendation.
func (mr *MockStoreMockRecorder) GetRecommendation(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecommendation", reflect.TypeOf((*MockStore)(nil).GetRecommendation), arg0, arg1)
}

// GetSummary mocks base method.
func (m *MockStore) GetSummary(arg0 context.Context, arg1 db.GetSummaryParams) (db.Summary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSummary", arg0, arg1)
	ret0, _ := ret[0].(db.Summary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSummary indicates an expected call of GetSummary.
func (mr *MockStoreMockRecorder) GetSummary(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSummary", reflect.TypeOf((*MockStore)(nil).GetSummary), arg0, arg1)
}

// GetTranscript mocks base method.
func (m *MockStore) GetTranscript(arg0 context.Context, arg1 int64) (db.Transcript, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTranscript", arg0, arg1)
	ret0, _ := ret[0].(db.Transcript)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTranscript indicates an expected call of GetTranscript.
func (mr *MockStoreMockRecorder) GetTranscript(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTranscript", reflect.TypeOf((*MockStore)(nil).GetTranscript), arg0, arg1)
}

// GetUser mocks base method.
func (m *MockStore) GetUser(arg0 context.Context, arg1 string) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", arg0, arg1)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockStoreMockRecorder) GetUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockStore)(nil).GetUser), arg0, arg1)
}

// ListAllCourses mocks base method.
func (m *MockStore) ListAllCourses(arg0 context.Context) ([]db.Course, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllCourses", arg0)
	ret0, _ := ret[0].([]db.Course)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllCourses indicates an expected call of ListAllCourses.
func (mr *MockStoreMockRecorder) ListAllCourses(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllCourses", reflect.TypeOf((*MockStore)(nil).ListAllCourses), arg0)
}

// ListCourses mocks base method.
func (m *MockStore) ListCourses(arg0 context.Context, arg1 int64) ([]db.Course, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCourses", arg0, arg1)
	ret0, _ := ret[0].([]db.Course)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCourses indicates an expected call of ListCourses.
func (mr *MockStoreMockRecorder) ListCourses(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCourses", reflect.TypeOf((*MockStore)(nil).ListCourses), arg0, arg1)
}

// ListRecentScholarshipsByUser mocks base method.
func (m *MockStore) ListRecentScholarshipsByUser(arg0 context.Context, arg1 db.ListRecentScholarshipsByUserParams) ([]db.Scholarship, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRecentScholarshipsByUser", arg0, arg1)
	ret0, _ := ret[0].([]db.Scholarship)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRecentScholarshipsByUser indicates an expected call of ListRecentScholarshipsByUser.
func (mr *MockStoreMockRecorder) ListRecentScholarshipsByUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRecentScholarshipsByUser", reflect.TypeOf((*MockStore)(nil).ListRecentScholarshipsByUser), arg0, arg1)
}

// ListRecommendations mocks base method.
func (m *MockStore) ListRecommendations(arg0 context.Context, arg1 string) ([]db.ListRecommendationsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRecommendations", arg0, arg1)
	ret0, _ := ret[0].([]db.ListRecommendationsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRecommendations indicates an expected call of ListRecommendations.
func (mr *MockStoreMockRecorder) ListRecommendations(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRecommendations", reflect.TypeOf((*MockStore)(nil).ListRecommendations), arg0, arg1)
}

// ListScholarshipsByUser mocks base method.
func (m *MockStore) ListScholarshipsByUser(arg0 context.Context, arg1 string) ([]db.Scholarship, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListScholarshipsByUser", arg0, arg1)
	ret0, _ := ret[0].([]db.Scholarship)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListScholarshipsByUser indicates an expected call of ListScholarshipsByUser.
func (mr *MockStoreMockRecorder) ListScholarshipsByUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListScholarshipsByUser", reflect.TypeOf((*MockStore)(nil).ListScholarshipsByUser), arg0, arg1)
}

// ListSummaries mocks base method.
func (m *MockStore) ListSummaries(arg0 context.Context, arg1 string) ([]db.Summary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSummaries", arg0, arg1)
	ret0, _ := ret[0].([]db.Summary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSummaries indicates an expected call of ListSummaries.
func (mr *MockStoreMockRecorder) ListSummaries(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSummaries", reflect.TypeOf((*MockStore)(nil).ListSummaries), arg0, arg1)
}

// ListTranscripts mocks base method.
func (m *MockStore) ListTranscripts(arg0 context.Context, arg1 string) ([]db.ListTranscriptsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTranscripts", arg0, arg1)
	ret0, _ := ret[0].([]db.ListTranscriptsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTranscripts indicates an expected call of ListTranscripts.
func (mr *MockStoreMockRecorder) ListTranscripts(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTranscripts", reflect.TypeOf((*MockStore)(nil).ListTranscripts), arg0, arg1)
}
