// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: course.sql

package db

import (
	"context"
	"database/sql"
)

const createCourse = `-- name: CreateCourse :one

INSERT INTO courses (
  code, name, language, grading_scale, organiser,
  learning_outcomes, prerequisites, teacher_name, teacher_email, course_link
) VALUES (
  $1,   $2,   $3,       $4,            $5,
  $6,               $7,           $8,          $9,           $10
)
RETURNING id, code, name, language, grading_scale, organiser, learning_outcomes, prerequisites, teacher_name, teacher_email, course_link, created_at
`

type CreateCourseParams struct {
	Code             string         `json:"code"`
	Name             string         `json:"name"`
	Language         sql.NullString `json:"language"`
	GradingScale     sql.NullString `json:"grading_scale"`
	Organiser        sql.NullString `json:"organiser"`
	LearningOutcomes sql.NullString `json:"learning_outcomes"`
	Prerequisites    sql.NullString `json:"prerequisites"`
	TeacherName      sql.NullString `json:"teacher_name"`
	TeacherEmail     sql.NullString `json:"teacher_email"`
	CourseLink       sql.NullString `json:"course_link"`
}

// server/db/query/course.sql
func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error) {
	row := q.db.QueryRowContext(ctx, createCourse,
		arg.Code,
		arg.Name,
		arg.Language,
		arg.GradingScale,
		arg.Organiser,
		arg.LearningOutcomes,
		arg.Prerequisites,
		arg.TeacherName,
		arg.TeacherEmail,
		arg.CourseLink,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Language,
		&i.GradingScale,
		&i.Organiser,
		&i.LearningOutcomes,
		&i.Prerequisites,
		&i.TeacherName,
		&i.TeacherEmail,
		&i.CourseLink,
		&i.CreatedAt,
	)
	return i, err
}

const listAllCourses = `-- name: ListAllCourses :many
SELECT id, code, name, language, grading_scale, organiser, learning_outcomes, prerequisites, teacher_name, teacher_email, course_link, created_at FROM courses ORDER BY id ASC
`

func (q *Queries) ListAllCourses(ctx context.Context) ([]Course, error) {
	rows, err := q.db.QueryContext(ctx, listAllCourses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Course{}
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Language,
			&i.GradingScale,
			&i.Organiser,
			&i.LearningOutcomes,
			&i.Prerequisites,
			&i.TeacherName,
			&i.TeacherEmail,
			&i.CourseLink,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCourses = `-- name: ListCourses :many
SELECT id, code, name, language, grading_scale, organiser, learning_outcomes, prerequisites, teacher_name, teacher_email, course_link, created_at FROM courses
ORDER BY id
LIMIT $1
`

func (q *Queries) ListCourses(ctx context.Context, limit int64) ([]Course, error) {
	rows, err := q.db.QueryContext(ctx, listCourses, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Course{}
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Language,
			&i.GradingScale,
			&i.Organiser,
			&i.LearningOutcomes,
			&i.Prerequisites,
			&i.TeacherName,
			&i.TeacherEmail,
			&i.CourseLink,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
