// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// server/db/query/course.sql
	CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error)
	// db/query/recommendation.sql
	CreateRecommendation(ctx context.Context, arg CreateRecommendationParams) (Recommendation, error)
	// db/query/scholarship.sql
	CreateScholarship(ctx context.Context, arg CreateScholarshipParams) (Scholarship, error)
	// db/query/summary.sql
	CreateSummary(ctx context.Context, arg CreateSummaryParams) (Summary, error)
	// db/query/transcript.sql
	CreateTranscript(ctx context.Context, arg CreateTranscriptParams) (Transcript, error)
	// db/query/user.sql
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteScholarship(ctx context.Context, arg DeleteScholarshipParams) error
	DeleteSummary(ctx context.Context, arg DeleteSummaryParams) error
	GetRecommendation(ctx context.Context, id int64) (Recommendation, error)
	GetSummary(ctx context.Context, arg GetSummaryParams) (Summary, error)
	GetTranscript(ctx context.Context, id int64) (Transcript, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListAllCourses(ctx context.Context) ([]Course, error)
	ListCourses(ctx context.Context, limit int64) ([]Course, error)
	ListRecentScholarshipsByUser(ctx context.Context, arg ListRecentScholarshipsByUserParams) ([]Scholarship, error)
	ListRecommendations(ctx context.Context, userUsername string) ([]ListRecommendationsRow, error)
	ListScholarshipsByUser(ctx context.Context, userUsername string) ([]Scholarship, error)
	ListSummaries(ctx context.Context, userUsername string) ([]Summary, error)
	ListTranscripts(ctx context.Context, userUsername string) ([]ListTranscriptsRow, error)
	UpdateRecommendationPayload(ctx context.Context, arg UpdateRecommendationPayloadParams) (Recommendation, error)
}

var _ Querier = (*Queries)(nil)
