// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recommendation.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const createRecommendation = `-- name: CreateRecommendation :one
INSERT INTO recommendations (
  user_username, transcript_id, summary, payload
) VALUES ($1, $2, $3, $4)
RETURNING id, user_username, transcript_id, summary, payload, created_at
`

type CreateRecommendationParams struct {
	UserUsername string          `json:"user_username"`
	TranscriptID sql.NullInt64   `json:"transcript_id"`
	Summary      sql.NullString  `json:"summary"`
	Payload      json.RawMessage `json:"payload"`
}

// db/query/recommendation.sql
func (q *Queries) CreateRecommendation(ctx context.Context, arg CreateRecommendationParams) (Recommendation, error) {
	row := q.db.QueryRowContext(ctx, createRecommendation,
		arg.UserUsername,
		arg.TranscriptID,
		arg.Summary,
		arg.Payload,
	)
	var i Recommendation
	err := row.Scan(
		&i.ID,
		&i.UserUsername,
		&i.TranscriptID,
		&i.Summary,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const getRecommendation = `-- name: GetRecommendation :one
SELECT id, user_username, transcript_id, summary, payload, created_at FROM recommendations WHERE id = $1 LIMIT 1
`

func (q *Queries) GetRecommendation(ctx context.Context, id int64) (Recommendation, error) {
	row := q.db.QueryRowContext(ctx, getRecommendation, id)
	var i Recommendation
	err := row.Scan(
		&i.ID,
		&i.UserUsername,
		&i.TranscriptID,
		&i.Summary,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const listRecommendations = `-- name: ListRecommendations :many
SELECT id, user_username, transcript_id, summary, created_at
FROM recommendations
WHERE user_username = $1
ORDER BY id DESC
`

type ListRecommendationsRow struct {
	ID           int64          `json:"id"`
	UserUsername string         `json:"user_username"`
	TranscriptID sql.NullInt64  `json:"transcript_id"`
	Summary      sql.NullString `json:"summary"`
	CreatedAt    time.Time      `json:"created_at"`
}

func (q *Queries) ListRecommendations(ctx context.Context, userUsername string) ([]ListRecommendationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecommendations, userUsername)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecommendationsRow{}
	for rows.Next() {
		var i ListRecommendationsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserUsername,
			&i.TranscriptID,
			&i.Summary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecommendationPayload = `-- name: UpdateRecommendationPayload :one
UPDATE recommendations
SET payload = $1
WHERE id = $2 AND user_username = $3
RETURNING id, user_username, transcript_id, summary, payload, created_at
`

type UpdateRecommendationPayloadParams struct {
	Payload      json.RawMessage `json:"payload"`
	ID           int64           `json:"id"`
	UserUsername string          `json:"user_username"`
}

func (q *Queries) UpdateRecommendationPayload(ctx context.Context, arg UpdateRecommendationPayloadParams) (Recommendation, error) {
	row := q.db.QueryRowContext(ctx, updateRecommendationPayload, arg.Payload, arg.ID, arg.UserUsername)
	var i Recommendation
	err := row.Scan(
		&i.ID,
		&i.UserUsername,
		&i.TranscriptID,
		&i.Summary,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}
