// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scholarship.sql

package db

import (
	"context"
	"database/sql"
)

const createScholarship = `-- name: CreateScholarship :one
INSERT INTO scholarships (
  user_username, title, description, match_score, link
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, user_username, title, description, match_score, link, created_at
`

type CreateScholarshipParams struct {
	UserUsername string          `json:"user_username"`
	Title        string          `json:"title"`
	Description  sql.NullString  `json:"description"`
	MatchScore   sql.NullFloat64 `json:"match_score"`
	Link         sql.NullString  `json:"link"`
}

// db/query/scholarship.sql
func (q *Queries) CreateScholarship(ctx context.Context, arg CreateScholarshipParams) (Scholarship, error) {
	row := q.db.QueryRowContext(ctx, createScholarship,
		arg.UserUsername,
		arg.Title,
		arg.Description,
		arg.MatchScore,
		arg.Link,
	)
	var i Scholarship
	err := row.Scan(
		&i.ID,
		&i.UserUsername,
		&i.Title,
		&i.Description,
		&i.MatchScore,
		&i.Link,
		&i.CreatedAt,
	)
	return i, err
}

const deleteScholarship = `-- name: DeleteScholarship :exec
DELETE FROM scholarships
WHERE id = $1 AND user_username = $2
`

type DeleteScholarshipParams struct {
	ID           int64  `json:"id"`
	UserUsername string `json:"user_username"`
}

func (q *Queries) DeleteScholarship(ctx context.Context, arg DeleteScholarshipParams) error {
	_, err := q.db.ExecContext(ctx, deleteScholarship, arg.ID, arg.UserUsername)
	return err
}

const listRecentScholarshipsByUser = `-- name: ListRecentScholarshipsByUser :many
SELECT id, user_username, title, description, match_score, link, created_at FROM scholarships
WHERE user_username = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListRecentScholarshipsByUserParams struct {
	UserUsername string `json:"user_username"`
	Limit        int64  `json:"limit"`
}

func (q *Queries) ListRecentScholarshipsByUser(ctx context.Context, arg ListRecentScholarshipsByUserParams) ([]Scholarship, error) {
	rows, err := q.db.QueryContext(ctx, listRecentScholarshipsByUser, arg.UserUsername, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Scholarship{}
	for rows.Next() {
		var i Scholarship
		if err := rows.Scan(
			&i.ID,
			&i.UserUsername,
			&i.Title,
			&i.Description,
			&i.MatchScore,
			&i.Link,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScholarshipsByUser = `-- name: ListScholarshipsByUser :many
SELECT id, user_username, title, description, match_score, link, created_at FROM scholarships
WHERE user_username = $1
ORDER BY match_score DESC
`

func (q *Queries) ListScholarshipsByUser(ctx context.Context, userUsername string) ([]Scholarship, error) {
	rows, err := q.db.QueryContext(ctx, listScholarshipsByUser, userUsername)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Scholarship{}
	for rows.Next() {
		var i Scholarship
		if err := rows.Scan(
			&i.ID,
			&i.UserUsername,
			&i.Title,
			&i.Description,
			&i.MatchScore,
			&i.Link,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
