// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: summary.sql

package db

import (
	"context"
	"database/sql"
)

const createSummary = `-- name: CreateSummary :one
INSERT INTO summaries (
  user_username, recommendation_id, summary_text, pdf_path
) VALUES ($1, $2, $3, $4)
RETURNING id, user_username, recommendation_id, summary_text, pdf_path, created_at
`

type CreateSummaryParams struct {
	UserUsername     string         `json:"user_username"`
	RecommendationID sql.NullInt64  `json:"recommendation_id"`
	SummaryText      sql.NullString `json:"summary_text"`
	PdfPath          sql.NullString `json:"pdf_path"`
}

// db/query/summary.sql
func (q *Queries) CreateSummary(ctx context.Context, arg CreateSummaryParams) (Summary, error) {
	row := q.db.QueryRowContext(ctx, createSummary,
		arg.UserUsername,
		arg.RecommendationID,
		arg.SummaryText,
		arg.PdfPath,
	)
	var i Summary
	err := row.Scan(
		&i.ID,
		&i.UserUsername,
		&i.RecommendationID,
		&i.SummaryText,
		&i.PdfPath,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSummary = `-- name: DeleteSummary :exec
DELETE FROM summaries
WHERE id = $1
  AND user_username = $2
`

type DeleteSummaryParams struct {
	ID           int64  `json:"id"`
	UserUsername string `json:"user_username"`
}

func (q *Queries) DeleteSummary(ctx context.Context, arg DeleteSummaryParams) error {
	_, err := q.db.ExecContext(ctx, deleteSummary, arg.ID, arg.UserUsername)
	return err
}

const getSummary = `-- name: GetSummary :one
SELECT id, user_username, recommendation_id, summary_text, pdf_path, created_at
FROM summaries
WHERE id = $1
  AND user_username = $2
LIMIT 1
`

type GetSummaryParams struct {
	ID           int64  `json:"id"`
	UserUsername string `json:"user_username"`
}

func (q *Queries) GetSummary(ctx context.Context, arg GetSummaryParams) (Summary, error) {
	row := q.db.QueryRowContext(ctx, getSummary, arg.ID, arg.UserUsername)
	var i Summary
	err := row.Scan(
		&i.ID,
		&i.UserUsername,
		&i.RecommendationID,
		&i.SummaryText,
		&i.PdfPath,
		&i.CreatedAt,
	)
	return i, err
}

const listSummaries = `-- name: ListSummaries :many
SELECT id, user_username, recommendation_id, summary_text, pdf_path, created_at
FROM summaries
WHERE user_username = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSummaries(ctx context.Context, userUsername string) ([]Summary, error) {
	rows, err := q.db.QueryContext(ctx, listSummaries, userUsername)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Summary{}
	for rows.Next() {
		var i Summary
		if err := rows.Scan(
			&i.ID,
			&i.UserUsername,
			&i.RecommendationID,
			&i.SummaryText,
			&i.PdfPath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
