// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transcript.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createTranscript = `-- name: CreateTranscript :one
INSERT INTO transcripts (
  user_username, file_path, text_extracted, meta
) VALUES ($1, $2, $3, $4)
RETURNING id, user_username, file_path, text_extracted, meta, created_at
`

type CreateTranscriptParams struct {
	UserUsername  string                `json:"user_username"`
	FilePath      string                `json:"file_path"`
	TextExtracted sql.NullString        `json:"text_extracted"`
	Meta          []byte         		`json:"meta"`
}

// db/query/transcript.sql
func (q *Queries) CreateTranscript(ctx context.Context, arg CreateTranscriptParams) (Transcript, error) {
	row := q.db.QueryRowContext(ctx, createTranscript,
		arg.UserUsername,
		arg.FilePath,
		arg.TextExtracted,
		arg.Meta,
	)
	var i Transcript
	err := row.Scan(
		&i.ID,
		&i.UserUsername,
		&i.FilePath,
		&i.TextExtracted,
		&i.Meta,
		&i.CreatedAt,
	)
	return i, err
}

const getTranscript = `-- name: GetTranscript :one
SELECT id, user_username, file_path, text_extracted, meta, created_at FROM transcripts WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTranscript(ctx context.Context, id int64) (Transcript, error) {
	row := q.db.QueryRowContext(ctx, getTranscript, id)
	var i Transcript
	err := row.Scan(
		&i.ID,
		&i.UserUsername,
		&i.FilePath,
		&i.TextExtracted,
		&i.Meta,
		&i.CreatedAt,
	)
	return i, err
}

const listTranscripts = `-- name: ListTranscripts :many
SELECT id, user_username, file_path, created_at
FROM transcripts
WHERE user_username = $1
ORDER BY id DESC
`

type ListTranscriptsRow struct {
	ID           int64     `json:"id"`
	UserUsername string    `json:"user_username"`
	FilePath     string    `json:"file_path"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) ListTranscripts(ctx context.Context, userUsername string) ([]ListTranscriptsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTranscripts, userUsername)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTranscriptsRow{}
	for rows.Next() {
		var i ListTranscriptsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserUsername,
			&i.FilePath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
